name: Production Deploy Workflow

on:
  release:
    types:
      - published
    branches:
      - main
  workflow_dispatch:

jobs:

  retag:
    runs-on: ubuntu-latest
    name: Retag image for deploy
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: echo "Retag image from tag ${{ github.sha }} to ${{ steps.get_version.outputs.VERSION }}"
      - run: docker pull ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }}
      - run: docker tag ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ steps.get_version.outputs.VERSION }}
      - run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ steps.get_version.outputs.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy via argoCD
    needs: retag
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "zeabix-cloud-native/pttgc-devops-lab10-cd"
          ref: 'main'
          token: ${{ secrets.CD_PAT }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: echo "Retag image from tag ${{ github.sha }} to ${{ steps.get_version.outputs.VERSION }}"
      - name: Update image version
        run: yq -i e '.userService.tag="${{ steps.get_version.outputs.VERSION }}"' values.yaml
        working-directory: ./production
      - name: Commit & Push changes
        run: |
          git config --global user.email 'DevOps'
          git config --global user.name  'devops@zeabix.com'
          git add .
          git commit -m "CD deployment to production with tag ${{ github.ref }}"
          git push https://${{ secrets.CD_PAT }}@github.com/zeabix-cloud-native/pttgc-devops-lab10-cd.git
